apply plugin: 'io.osrsx.plugin'

osrsxPlugin {
    id = 'woodcutter'
    group = 'io.osrsx.plugins'
    version = '1.2.0'
    name = 'Woodcutter'
    description = 'Chops the best tree for your level and banks or drops the logs.'
    authors = ['osrsx']
    tags = ['skilling', 'woodcutting', 'gathering']
    requires 'skilling-lib:1.2.0'
}
